Для симетричної додатньо визначеної матриці А побудувати модельний приклад:
* побудувати довільний вектор x

* обчислити вектор b правої частини

* для матриці A, обчислити її визначник та число обумовленості

Розв'язати СЛАР Ax=b методами:

* Простої ітерації з оптимальним параметром,

* методом Зейделя з коефіцієнтом 0.2,

* методом Річардсона p=5.

Всі розв'язки знаходити з точністю е = 10^-3.

Ці методи реалізуються самостійно.

Можна використовувати методи: numpy.linalg.cond, numpy.linalg.det, numpy.linalg.eigvals, numpy.linalg.norm, A.dot(b).
Неможна використовувати методи, які автоматично розраховують вказані в завданні ітераційні методи.

In [ ]:
import numpy as np

#n=3
#A=np.random.rand(n,n)
#b=np.random.rand(n)

A=np.array([[10,2,1],[2,8,1],[1,1,5]],dtype=float)
xT=np.array([[2],[5],[8]])
b=np.dot(A,xT)

n=len(b)

x=np.zeros((n,1))
y=np.zeros((n,1))

print('A \n',A)
print('xT \n',xT)
print('b \n',b)
print(np.linalg.cond(A, 2), "число обумовленості програмно")
print(np.linalg.det(A), "визначник матриці А")

print()
print(np.linalg.eigvals(A),"власні значення")
eigvals = np.linalg.eigvals(A)

m = np.min(eigvals)
M = np.max(eigvals)
print('\nm =', m)
print('M =', M)

print()
alp=2/(m+M)
print(alp,'оптимальний параметр alpha')

n=3
x=np.zeros((n,1))
k=0
eps=1e-3
while True:
    x_new=x-alp*(A.dot(x)-b)
    #print(x_new)
    if np.linalg.norm(x_new-x)<eps:
        break
    x=x_new
    k+=1
    #print(k)

print('кількість ітерацій:', k)
print('розв’язок:')
print(x_new)

print('похибка:')
print(np.linalg.norm(x_new - xT))

condA=np.linalg.cond(A,2)
nu_iter=2/condA
print('теоретичний показник збіжності простої ітерації:', nu_iter)
nu_fact=(1/k)*np.log(np.linalg.norm(x-xT)/np.linalg.norm(x_new-xT))
print('фактичний показник збіжності:',nu_fact)

A 
 [[10.  2.  1.]
 [ 2.  8.  1.]
 [ 1.  1.  5.]]
xT 
 [[2]
 [5]
 [8]]
b 
 [[38.]
 [52.]
 [47.]]
2.4728012352165454 число обумовленості програмно
366.00000000000017 визначник матриці А

[11.52728869  6.81107958  4.66163173] власні значення

m = 4.6616317263833285
M = 11.527288691125335

0.12354128307635372 оптимальний параметр alpha
кількість ітерацій: 11
розв’язок:
[[1.99985452]
 [4.99994476]
 [7.9997492 ]]
похибка:
0.00029515675206037223
теоретичний показник збіжності простої ітерації: 0.8087993371714967
фактичний показник збіжності: 0.07798139555478155


In [ ]:
#Метод Зейделя
import numpy as np

#n=3
#A=np.random.rand(n,n)
#b=np.random.rand(n)

A=np.array([[10,2,1],[2,8,1],[1,1,5]],dtype=float)
xT=np.array([[2],[5],[8]])
b=np.dot(A,xT)

n=len(b)

x=np.zeros((n,1))
y=np.zeros((n,1))

print('A \n',A)
print('xT \n',xT)
print('b \n',b)
print(np.linalg.cond(A, 2), "число обумовленості програмно")
print(np.linalg.det(A), "визначник матриці А")
print(np.linalg.eigvals(A),"власні значення")
eigvals = np.linalg.eigvals(A)

m = np.min(eigvals)
M = np.max(eigvals)
print('m =', m)
print('M =', M)

print()
alp=2/(m+M)
print(alp,'оптимальний параметр alpha')

n=3
x=np.zeros((n,1))
k=0
eps=1e-3
while True:
    x_new = x.copy()
    for i in range(n):
        s1=0
        s2=0
        for j in range(i):
            s1+=A[i,j]*x_new[j]
        for j in range(i+1,n):
            s2+=A[i,j]*x[j]
        x_new[i]=(b[i]-s1-s2)/A[i,i]
    if np.linalg.norm(x_new-x)<eps:
        break
    x=x_new
    k+=1

print('кількість ітерацій:', k)
print('розв’язок:')
print(x_new)

print('похибка:')
print(np.linalg.norm(x_new-xT))

nu_fact=(1/k)*np.log(np.linalg.norm(x-xT)/np.linalg.norm(x_new-xT))
print('фактичний показник збіжності:',nu_fact)

A 
 [[10.  2.  1.]
 [ 2.  8.  1.]
 [ 1.  1.  5.]]
xT 
 [[2]
 [5]
 [8]]
b 
 [[38.]
 [52.]
 [47.]]
2.4728012352165454 число обумовленості програмно
366.00000000000017 визначник матриці А
[11.52728869  6.81107958  4.66163173] власні значення
m = 4.6616317263833285
M = 11.527288691125335

0.12354128307635372 оптимальний параметр alpha
кількість ітерацій: 5
розв’язок:
[[2.00000349]
 [4.99999817]
 [7.99999967]]
похибка:
3.950684237450657e-06
фактичний показник збіжності: 0.3942405327804973


In [ ]:
#Метод Річардсона p=5
import numpy as np

#n=3
#A=np.random.rand(n,n)
#b=np.random.rand(n)

A=np.array([[10,2,1],[2,8,1],[1,1,5]],dtype=float)
xT=np.array([[2],[5],[8]])
b=np.dot(A,xT)

n=len(b)

x=np.zeros((n,1))
y=np.zeros((n,1))

print('A \n',A)
print('xT \n',xT)
print('b \n',b)
print(np.linalg.cond(A, 2), "число обумовленості програмно")
print(np.linalg.det(A), "визначник матриці А")
print(np.linalg.eigvals(A),"власні значення")
eigvals = np.linalg.eigvals(A)
m = np.min(eigvals)
M = np.max(eigvals)
print('m =', m)
print('M =', M)

p=5
alp=[]
for i in range(p):
    alpi=1/(((M-m)/2)*np.cos((2*i+1)*np.pi/(2*p))+((M+m)/2))
    alp.append(alpi)
print()
print(alp,'параметри alpha i')

n=3
x=np.zeros((n,1))
k=0
eps=1e-3
while True:
    x_old=x.copy()
    for i in range(p):
        x=x-alp[i]*(A.dot(x)-b)
    k+=p
    if np.linalg.norm(x-x_old)<eps:
        break

print('кількість ітерацій:',k)
print('розв’язок:')
print(x)

print('похибка:')
print(np.linalg.norm(x-xT))

nu_rich=2/np.sqrt(condA)
print('теоретичний показник збіжності Річардсона:',nu_rich)

nu_fact=(1/k)*np.log(np.linalg.norm(x_old-xT)/np.linalg.norm(x-xT))
print('фактичний показник збіжності:',nu_fact)

A 
 [[10.  2.  1.]
 [ 2.  8.  1.]
 [ 1.  1.  5.]]
xT 
 [[2]
 [5]
 [8]]
b 
 [[38.]
 [52.]
 [47.]]
2.4728012352165454 число обумовленості програмно
366.00000000000017 визначник матриці А
[11.52728869  6.81107958  4.66163173] власні значення
m = 4.6616317263833285
M = 11.527288691125335

[np.float64(0.08803379429420971), np.float64(0.09889019329158896), np.float64(0.12354128307635372), np.float64(0.1645631585757028), np.float64(0.20705449955333707)] параметри alpha i
кількість ітерацій: 15
розв’язок:
[[2.00000001]
 [5.        ]
 [7.99999999]]
похибка:
1.2198462401305362e-08
теоретичний показник збіжності Річардсона: 1.271848526493227
фактичний показник збіжності: 0.4552303764534036
