Зі 11 стр. методичний вказівок "Методи обчислень. Ч.2. Методичні вказівки" зробити пункти 1, 5, 6 (Часткова проблема власних значень).

Мовою пакету Octave написати програми степеневого методу та методу
зворотної iтерацiї.
Провести наступний обчислювальний експеримент. Для заданої матрицi
A iз заданою точнiстю ε:
1. знайти найбiльше i найменше власнi значення степеневим методом;
5. знайти найближче до заданого числа α власне значення;
6. порiвняти швидкiсть збiжностi зворотної iтерацiї та зворотної iтерацiї з
зсувом Релея для знаходження мiнiмального за модулем власного значення.

Можна використовувати всі методи. np.linalg.eigvals і його аналогі, використовувати тільки для перевірки знайдених заданими методами результатів. Задані методи пишемо самостійно. Матриці задані у відповідних завданнях.

In [ ]:
import numpy as np
import math
from scipy.linalg import solve

def lu_solve(A,b):
  n=len(b)
  L=np.eye((n))
  U=A.copy()

  #1. Прямий хід: LU-розклад
  for k in range(n):
    if U[k][k]==0:
      print("Error")
    else:
      for i in range(k+1,n):
        N=U[i][k]/U[k][k]
        L[i][k]=-N
        for j in range(k,n):
          U[i][j]=U[i][j]+N*U[k][j]
  #2 Пряма підстановка: Вирішуємо Ly=b

  y=np.zeros((n,1))
  for k in range(n):
    y[k]=b[k]
    for i in range(k):
      y[k]=y[k]-L[k][i]*y[i]
    y[k]=y[k]/L[k][k]

  #3 Зворотня підстановка: Ux=y

  x=np.zeros((n,1))

  for k in range(n-1,-1,-1):
    x[k]=y[k]
    for i in range(k+1,n):
      x[k]=x[k]-U[k][i]*x[i]
    x[k]=x[k]/U[k][k]

  return x,L,U

A=np.random.rand(4,4)
#A=np.array([[10,2,1],[2,8,1],[1,1,5]],dtype=float)
print("Matrix A:\n", A)
b=np.random.rand(4)
#b=np.array([[2],[5],[8]])
print("vector b:\n", b)

x=lu_solve(A,b)
print("Solution:\n",x)
print("Число обумовленості:\n", np.linalg.cond(A,2))
print("Check A and b:\n", np.dot(A,b))

print(np.linalg.eigvals(A),"власні значення")




Matrix A:
 [[0.58 1.   0.6  0.09]
 [0.19 0.92 0.57 0.1 ]
 [0.79 0.66 0.08 0.57]
 [0.33 0.43 0.49 0.44]]
vector b:
 [0.55 0.67 0.59 0.52]
Solution:
 (array([[-0.17],
       [ 0.33],
       [ 0.09],
       [ 2.75]]), array([[ 1.  ,  0.  ,  0.  ,  0.  ],
       [-0.33,  1.  ,  0.  ,  0.  ],
       [-1.37, -1.61,  1.  ,  0.  ],
       [-0.57, -0.8 , -0.67,  1.  ]]), array([[0.58, 1.  , 0.6 , 0.09],
       [0.39, 1.25, 0.77, 0.13],
       [1.58, 4.05, 2.15, 0.91],
       [0.66, 2.  , 2.9 , 1.21]]))
Число обумовленості:
 12.824499734469095
Check A and b:
 [1.39 1.11 1.22 0.98]
[ 1.96+0.j   -0.49+0.j    0.27+0.11j  0.27-0.11j] власні значення


In [ ]:
import numpy as np
import numpy as np
import math
from scipy.linalg import solve


n=20
k=2
alp=10+k/10
e=10^(-10)

C = np.zeros((n, n))

for i in range(n):
    for j in range(n):
        if i==j:
            C[i,j]=alp if i%2==0 else-alp
        else:
            C[i,j]=(i+1+j+1)/alp

np.set_printoptions(precision=2, suppress=True)
print(C)


[[ 10.2    0.29   0.39   0.49   0.59   0.69   0.78   0.88   0.98   1.08
    1.18   1.27   1.37   1.47   1.57   1.67   1.76   1.86   1.96   2.06]
 [  0.29 -10.2    0.49   0.59   0.69   0.78   0.88   0.98   1.08   1.18
    1.27   1.37   1.47   1.57   1.67   1.76   1.86   1.96   2.06   2.16]
 [  0.39   0.49  10.2    0.69   0.78   0.88   0.98   1.08   1.18   1.27
    1.37   1.47   1.57   1.67   1.76   1.86   1.96   2.06   2.16   2.25]
 [  0.49   0.59   0.69 -10.2    0.88   0.98   1.08   1.18   1.27   1.37
    1.47   1.57   1.67   1.76   1.86   1.96   2.06   2.16   2.25   2.35]
 [  0.59   0.69   0.78   0.88  10.2    1.08   1.18   1.27   1.37   1.47
    1.57   1.67   1.76   1.86   1.96   2.06   2.16   2.25   2.35   2.45]
 [  0.69   0.78   0.88   0.98   1.08 -10.2    1.27   1.37   1.47   1.57
    1.67   1.76   1.86   1.96   2.06   2.16   2.25   2.35   2.45   2.55]
 [  0.78   0.88   0.98   1.08   1.18   1.27  10.2    1.47   1.57   1.67
    1.76   1.86   1.96   2.06   2.16   2.25   2.35   2.45 

In [ ]:


def PowerIter(A,eps):
  n=5
  y=np.ones(n)
  x=y/np.linalg.norm(y,ord=2)
  lam=0
  lam1=0
  for i in range(20):
    y=C.dot(x)
    lam=lam1
    lam1=y.T.dot(x)
    x=y/np.linalg.norm(y,ord=2)
    if(abs(lam1-lam)<eps*lam1):
      break
  return lam, y
PowerIter(C, 0.1)



NameError: name 'C' is not defined

In [ ]:
import numpy as np

n=20
k=2
alp=10+k/10
eps=1e-10
max_i=1000
max_i

A = np.zeros((n, n))

for i in range(n):
    for j in range(n):
        if i==j:
            A[i,j]=alp if i%2==0 else-alp
        else:
            A[i,j]=(i+1+j+1)/alp

print("Матриця A:\n",A)

# cтепеневий метод

def power_method(A, eps=1e-10, max_i=1000):
    n=A.shape[0]
    y0=np.ones(n)
    x=y0/np.linalg.norm(y0)
    l_old=0

    for k in range(max_i):
        # y(k+1) = A*x(k)
        y=A@x
        #lambda(k+1)
        l_new=np.dot(y, x)
        # нормування
        x=y/np.linalg.norm(y)
        # перевірка збіжності
        if abs(l_new-l_old)<=eps*abs(l_new):
            break
        l_old=l_new

    return l_new, x, k + 1

# зворотна ітерація

def inverse_iteration(A, eps=1e-10, max_i=1000):
    n=A.shape[0]
    y0=np.ones(n)
    x=y0/np.linalg.norm(y0)
    l_old=0

    for k in range(max_i):
        # A*y = x
        y=np.linalg.solve(A,x)
        # оцінка власного значення
        mu=np.dot(y,x)
        l_new=1/mu
        # нормування
        x=y/np.linalg.norm(y)
        # критерій зупинки
        if abs(l_new-l_old)<=eps*abs(l_new):
            break
        l_old=l_new
    return l_new, x, k + 1


# зворотна ітерація зі зсувом

def shifted_inverse_iteration(A, sigma, eps=1e-10, max_i=1000):
    n=A.shape[0]
    y0=np.ones(n)
    x=y0/np.linalg.norm(y0)
    I=np.eye(n)
    l_old=0

    for k in range(max_i):
        # (A - sigma*I)y = x
        y=np.linalg.solve(A-sigma * I,x)
        x=y/np.linalg.norm(y)
        # відношення Релея
        l_new=x@A@x
        if abs(l_new-l_old)<=eps*abs(l_new):
            break
        l_old=l_new
    return l_new, x, k + 1

# зворотна ітерація зі зсувом Релея

def rayleigh_iteration(A, eps=1e-10, max_i=1000):
    n=A.shape[0]
    y0=np.ones(n)
    x=y0/np.linalg.norm(y0)
    I=np.eye(n)
    s=x@A@x

    for k in range(max_i):
        # (A - s*I)y = x
        y=np.linalg.solve(A-s*I,x)
        # нормування
        x=y/np.linalg.norm(y)
        # новий зсув Релея
        s_new=x@A@x
        # критерій зупинки
        if abs(s_new-s)<=eps*abs(s_new):
            break
        s=s_new
    return s_new, x, k + 1

print()
#1
# Найбільше власне значення
l_max, vec_max, iter_max=power_method(A,eps)

print("Найбільше власне значення:",l_max)
print("Кількість ітерацій:",iter_max)

# Найменше власне значення
l_min, vec_min, iter_min=inverse_iteration(A,eps)

print("Найменше власне значення:",l_min)
print("Кількість ітерацій:",iter_min)

#5
# Найближче до заданого alpha
sigma = 5
lambda_shift, vec_shift, iter_shift=shifted_inverse_iteration(A,sigma,eps)

print("Власне значення, найближче до sigma =", sigma)
print(lambda_shift)

print("Кількість ітерацій:",iter_shift)

#6
# Порівняння швидкості збіжності

lambda_rayleigh, vec_rayleigh, iter_rayleigh=rayleigh_iteration(A,eps)

print("\nМетод Релея:",lambda_rayleigh)
print("Кількість ітерацій:",iter_rayleigh)

# Перевірка через NumPy
print("Перевірка:\n",np.linalg.eigvals(A))


Матриця A:
 [[ 10.2          0.29411765   0.39215686   0.49019608   0.58823529
    0.68627451   0.78431373   0.88235294   0.98039216   1.07843137
    1.17647059   1.2745098    1.37254902   1.47058824   1.56862745
    1.66666667   1.76470588   1.8627451    1.96078431   2.05882353]
 [  0.29411765 -10.2          0.49019608   0.58823529   0.68627451
    0.78431373   0.88235294   0.98039216   1.07843137   1.17647059
    1.2745098    1.37254902   1.47058824   1.56862745   1.66666667
    1.76470588   1.8627451    1.96078431   2.05882353   2.15686275]
 [  0.39215686   0.49019608  10.2          0.68627451   0.78431373
    0.88235294   0.98039216   1.07843137   1.17647059   1.2745098
    1.37254902   1.47058824   1.56862745   1.66666667   1.76470588
    1.8627451    1.96078431   2.05882353   2.15686275   2.25490196]
 [  0.49019608   0.58823529   0.68627451 -10.2          0.88235294
    0.98039216   1.07843137   1.17647059   1.2745098    1.37254902
    1.47058824   1.56862745   1.66666667   1.764

In [ ]:
import numpy as np

In [ ]:
import numpy as np

A=np.array([[4,0],[1,3],[2,5]])

Rinv=np.linalg.inv(-np.linalg.qr(A)[1])
Qt=np.transpose(-np.linalg.qr(A)[0])

b=np.array([[3],[-3],[3]])
print("b\n",b)

print("Rinv\n",Rinv)
print("Qt\n",Qt)

X=Rinv@Qt@b
print("X\n",X)


b
 [[ 3]
 [-3]
 [ 3]]
Rinv
 [[ 0.21821789 -0.12151656]
 [ 0.          0.19629598]]
Qt
 [[ 0.87287156  0.21821789  0.43643578]
 [-0.48606623  0.46737137  0.73844677]]
X
 [[ 0.79266055]
 [-0.1266055 ]]
