In [ ]:
import numpy as np
#Боцу Алина LU

A=np.array([[5,-4,8],[7,6,-3],[-2,1,9]],dtype=float)
xT=np.array([[2],[5],[8]])
b=np.dot(A,xT)

n=len(b)

x=np.zeros((n,1))
y=np.zeros((n,1))

L=np.eye((n))
U=A.copy()

for k in range(n):
    if U[k][k]==0:
        print("Error")
    else:
        for i in range(k+1,n):
            N=-U[i][k]/U[k][k]
            L[i][k]=-N
            for j in range(k,n):
                U[i][j]=U[i][j]+N*U[k][j]

print('A \n',A)
print('xT \n',xT)
print('b \n',b)
print()
print('L \n',L)
print('U \n',U)
print('L@U \n',L@U)
print(np.linalg.cond(A, 2), "число обумовленості програмно")
print()

for k in range(n):
    y[k]=b[k]
    for i in range(k):
        y[k]=y[k]-L[k][i]*y[i]
    y[k]=y[k]/L[k][k]

print('y \n',y)

for k in range(n-1,-1,-1):
    x[k]=y[k]
    for i in range(k+1,n):
        x[k]=x[k]-U[k][i]*x[i]
    x[k]=x[k]/U[k][k]

print('x \n',x)

#тема 2 задание 1 методичка переделать под свой номер чистовой вариант

A 
 [[ 5. -4.  8.]
 [ 7.  6. -3.]
 [-2.  1.  9.]]
xT 
 [[2]
 [5]
 [8]]
b 
 [[54.]
 [20.]
 [73.]]

L 
 [[ 1.          0.          0.        ]
 [ 1.4         1.          0.        ]
 [-0.4        -0.05172414  1.        ]]
U 
 [[  5.          -4.           8.        ]
 [  0.          11.6        -14.2       ]
 [  0.           0.          11.46551724]]
L@U 
 [[ 5. -4.  8.]
 [ 7.  6. -3.]
 [-2.  1.  9.]]
2.347927982909794 число обумовленості програмно

y 
 [[ 54.        ]
 [-55.6       ]
 [ 91.72413793]]
x 
 [[2.]
 [5.]
 [8.]]
