In [ ]:
import numpy as np
#Боцу Алина Метод Гауса

#n=3
#A=np.random.rand(n,n)
#b=np.random.rand(n)

A=np.array([[2,1,0],[1,3,1],[6,1,1]],dtype=float)
b=np.array([[2],[2],[7]],dtype=float)

print("Матрица А \n", A)
print("Векор b \n",b)
print()

def metod_gausa(A, b):
    n = len(A)
    x = np.zeros(n)
    A = A.astype(float)
    b = b.astype(float)

    for k in range(n):
        if A[k][k]==0:
            print("Error")
        else:
            for i in range(k+1,n):
                N =  A[i][k] / A[k][k]
                A[i, k:] = A[i, k:] - N * A[k, k:]
                b[i] = b[i] - N * b[k]

    for k in range(n - 1, -1, -1):
        x[k] = b[k]
        for i in range(k + 1, n):
            x[k] -= A[k][i] * x[i]
        x[k] /= A[k][k]
    return x

x = metod_gausa(A, b)
print("\nПеревірка A @ x:", x)

print(np.dot(A, x))

Матрица А 
 [[2. 1. 0.]
 [1. 3. 1.]
 [6. 1. 1.]]
Векор b 
 [[2.]
 [2.]
 [7.]]


Перевірка A @ x: [1. 0. 1.]
[2. 2. 7.]


/tmp/ipykernel_10223/2655327821.py:31: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  x[k] = b[k]


In [ ]:
import numpy as np
#Боцу Алина Метод Гауса

n=5
A=np.random.rand(n,n)
b=np.random.rand(n)

print("Матрица А \n", A)
print("Векор b \n",b)
print()

def metod_gausa(A, b):
    n = len(A)
    x = np.zeros(n)
    A = A.astype(float)
    b = b.astype(float)

    for k in range(n):
        if A[k][k]==0:
            print("Error")
        else:
            for i in range(k+1,n):
                N =  A[i][k] / A[k][k]
                A[i, k:] = A[i, k:] - N * A[k, k:]
                b[i] = b[i] - N * b[k]

    for k in range(n - 1, -1, -1):
        x[k] = b[k]
        for i in range(k + 1, n):
            x[k] -= A[k][i] * x[i]
        x[k] /= A[k][k]
    return x

x = metod_gausa(A, b)
print("\nПеревірка A @ x:", x)

print(np.dot(A, x))

Матрица А 
 [[0.7026129  0.71132418 0.72527068 0.48844808 0.82860656]
 [0.68697036 0.62466602 0.23219991 0.95937669 0.55221567]
 [0.28632849 0.35142897 0.62601174 0.24928411 0.69904938]
 [0.25653086 0.2459391  0.65402    0.87953296 0.10778342]
 [0.45112815 0.40670552 0.98607653 0.82364128 0.0719243 ]]
Векор b 
 [0.02733717 0.33120419 0.33004647 0.17432025 0.48938219]


Перевірка A @ x: [ 36.73215642 -46.20938139   2.46236767  -0.22565622   6.53270062]
[0.02733717 0.33120419 0.33004647 0.17432025 0.48938219]


In [ ]:
import numpy as np
#Боцу Алина Метод Гауса

#n=3
#A=np.random.rand(n,n)
#b=np.random.rand(n)

A=np.array([[5,-4,8],[7,6,-3],[-2,1,9]],dtype=float)
b=np.array([[54],[20],[73]],dtype=float)

print("Матрица А \n", A)
print("Векор b \n",b)
print()

def metod_gausa(A, b):
    n = len(A)
    x = np.zeros(n)
    A = A.astype(float)
    b = b.astype(float)

    for k in range(n):
        if A[k][k]==0:
            print("Error")
        else:
            for i in range(k+1,n):
                N =  A[i][k] / A[k][k]
                A[i, k:] = A[i, k:] - N * A[k, k:]
                b[i] = b[i] - N * b[k]

    for k in range(n - 1, -1, -1):
        x[k] = b[k]
        for i in range(k + 1, n):
            x[k] -= A[k][i] * x[i]
        x[k] /= A[k][k]
    return x

x = metod_gausa(A, b)
print("\nПеревірка A @ x:", x)

print(np.dot(A, x))

Матрица А 
 [[ 5. -4.  8.]
 [ 7.  6. -3.]
 [-2.  1.  9.]]
Векор b 
 [[54.]
 [20.]
 [73.]]


Перевірка A @ x: [2. 5. 8.]
[54. 20. 73.]


/tmp/ipykernel_10223/1484141805.py:31: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  x[k] = b[k]


In [ ]:
import numpy as np
#Боцу Алина Метод Гауса з частковим вибором головного елементу, Метод обернень
#доделать, додати перевірку и перестановку строк
n=6
A=np.random.rand(n,n)
b=np.random.rand(n)

#A=np.array([[2,1,0],[1,3,1],[6,1,1]],dtype=float)
#b=np.array([[2],[2],[7]],dtype=float)

print("Матрица А \n", A)
print("Векор b \n",b)
print()

def metod_gausa(A, b):
    n = len(A)
    x = np.zeros(n)
    A = A.astype(float)
    b = b.astype(float)
#Метод Гауса з частковим вибором головного елементу
    p = np.arange(n)
    for k in range(n):
      max_val = 0
      max_i = k
      max_j = k
    for i in range(k, n):
      for j in range(k, n):
        if abs(A[i][j]) > max_val:
          max_val = abs(A[i][j])
          max_i = i
          max_j = j

    if max_val == 0:
      print("Матриця вироджена")
      return None

    if max_i != k:
      A[[k, max_i]] = A[[max_i, k]]
      b[[k, max_i]] = b[[max_i, k]]

    if max_j != k:
      A[:, [k, max_j]] = A[:, [max_j, k]]
      p[[k, max_j]] = p[[max_j, k]]
#МГ кінець

    for k in range(n):
        if A[k][k]==0:
            print("Error")
        else:
            for i in range(k+1,n):
                N =  A[i][k] / A[k][k]
                A[i, k:] = A[i, k:] - N * A[k, k:]
                b[i] = b[i] - N * b[k]

    for k in range(n - 1, -1, -1):
        x[k] = b[k]
        for i in range(k + 1, n):
            x[k] -= A[k][i] * x[i]
        x[k] /= A[k][k]
    return x

x = metod_gausa(A, b)
print("\nПеревірка A @ x:", x)

print(np.dot(A, x))

Матрица А 
 [[0.1441632  0.4664647  0.11337682 0.25283314 0.147052   0.16657637]
 [0.96940324 0.91059549 0.94652295 0.69061855 0.12954661 0.48543403]
 [0.37754221 0.99631534 0.00455605 0.22670357 0.1659468  0.63144021]
 [0.67336123 0.7296092  0.44655625 0.28490172 0.22252374 0.43175371]
 [0.94690568 0.69268377 0.64945364 0.93625712 0.38795194 0.47932659]
 [0.49993372 0.97107377 0.14200439 0.42591301 0.45509779 0.41449917]]
Векор b 
 [0.67073547 0.66730482 0.57365258 0.20211673 0.92586391 0.57066992]


Перевірка A @ x: [-5.8096249  -1.06197991  4.00349936  1.05292711  3.3138218   4.77992602]
[0.67073547 0.66730482 0.57365258 0.20211673 0.92586391 0.57066992]
